### ISSUE TITLE
save data in wizard on tab change

### ISSUE THREAD

**Issue by MoritzFago** [freifunk-gluon/gluon#1166] opened 2017-06-28 14:27 UTC
If you are in the config mode for the first time, enter something in the nodename field, change to the expert tab, to add a ssh-key and then get back, your entered data is lost. Instead it should be preserved, maybe in the browsers local storage or somewhere else, for the duration of the configuration session.

**Comment by NeoRaider** [comment] 2017-06-28 14:38
Duplicate of #131.

**Closed by NeoRaider** 2017-06-28 14:38 UTC
