### ISSUE TITLE
No wifi connection via Freifunk on 11s (TP-Link C59)

### ISSUE THREAD

**Issue by mokkin** [freifunk-gluon/gluon#1381] opened 2018-05-03 21:09 UTC
Private WLAN is working
Connection via WLAN on Freifunk AP not. After pressing "wifi" command it works again.
Firmware: http://firmware.leipzig.freifunk.net:8004/srv2/gluon/20180401/
(based on OpenWRT Trunk)
btw: 5 GHz mesh is disabled due to unstable ath10k

```
[542421.723705] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542422.723895] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542423.723777] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542424.724154] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542425.724058] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542426.724432] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542427.724478] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542428.724487] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542429.724587] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542430.724737] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542431.724857] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542432.725052] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542433.725044] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542434.725145] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542435.725480] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542436.725345] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542437.725520] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542438.725516] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542439.725643] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542440.726063] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542441.725872] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542442.726236] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542443.726375] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542444.726480] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542445.726506] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542446.726735] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542447.726583] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542448.726746] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542449.726900] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542450.727096] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542451.727025] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542452.727208] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542453.727516] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542454.727500] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542455.727710] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542456.727599] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542457.727660] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542458.457277] ath10k_pci 0000:00:00.0: No VIF found for vdev 1
[542458.463234] ath10k_pci 0000:00:00.0: received addba event for invalid vdev_id: 1
[542458.474536] ath10k_pci 0000:00:00.0: peer-unmap-event: unknown peer id 2
[542458.492444] br-client: port 5(client0) entered disabled state
[542458.503710] device client0 left promiscuous mode
[542458.508801] br-client: port 5(client0) entered disabled state
[542458.531325] br-client: port 4(client1) entered disabled state
[542458.570237] device client1 left promiscuous mode
[542458.575240] br-client: port 4(client1) entered disabled state
[542458.727940] ath10k_pci 0000:00:00.0: Spurious quick kickout for STA cc:fd:17:ec:a3:be
[542458.858176] device wlan0 left promiscuous mode
[542458.863116] br-wan: port 3(wlan0) entered disabled state
[542458.906145] ------------[ cut here ]------------
[542458.911219] WARNING: CPU: 0 PID: 2511 at backports-2017-11-01/net/mac80211/sta_info.c:940 ieee80211_sta_eosp+0x65c/0xa34 [mac80211]
[542458.923600] Modules linked in: ath9k nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute ath9k_common ath10k_pci ath10k_core xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mac80211 iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 br_netfilter ath9k_hw ath em_cmp em_nbyte sch_dsmark sch_pie sch_gred em_meta sch_teql
[542458.997255]  act_ipt sch_multiq sch_prio em_text sch_codel sch_red sch_sfq sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_htb sch_hfsc ledtrig_usbport batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables dummy ip_tunnel veth tun vxlan udp_tunnel ip6_udp_tunnel ehci_platform ehci_hcd act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug usbcore nls_base usb_common crc16 crc32c_generic crypto_hash
[542459.044716] CPU: 0 PID: 2511 Comm: hostapd Tainted: G        W       4.9.87 #0
[542459.052269] Stack : 804e765a 00000042 00000000 00000001 8658d724 8046b327 8041e800 000009cf
[542459.061057]         804e37a0 000003ac 87658fcc 00000001 87658fcc 800a9240 80424030 80470000
[542459.069847]         00000003 000003ac 804221e8 86671a7c 87658fcc 800d6f6c 804e765a 00000077
[542459.078637]         8047d000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.087427]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.096217]         ...
[542459.098843] Call Trace:
[542459.101459] [<8006b0f0>] show_stack+0x70/0x8c
[542459.106073] [<80080064>] __warn+0x110/0x118
[542459.110482] [<80080100>] warn_slowpath_null+0x1c/0x2c
[542459.115906] [<87783ed4>] ieee80211_sta_eosp+0x65c/0xa34 [mac80211]
[542459.122416] ---[ end trace d2e6a234c6756785 ]---
[542459.127282] ------------[ cut here ]------------
[542459.132204] WARNING: CPU: 0 PID: 2511 at backports-2017-11-01/net/mac80211/sta_info.c:1120 __sta_info_flush+0x158/0x198 [mac80211]
[542459.144420] Modules linked in: ath9k nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute ath9k_common ath10k_pci ath10k_core xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mac80211 iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 br_netfilter ath9k_hw ath em_cmp em_nbyte sch_dsmark sch_pie sch_gred em_meta sch_teql
[542459.218046]  act_ipt sch_multiq sch_prio em_text sch_codel sch_red sch_sfq sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_htb sch_hfsc ledtrig_usbport batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables dummy ip_tunnel veth tun vxlan udp_tunnel ip6_udp_tunnel ehci_platform ehci_hcd act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug usbcore nls_base usb_common crc16 crc32c_generic crypto_hash
[542459.265497] CPU: 0 PID: 2511 Comm: hostapd Tainted: G        W       4.9.87 #0
[542459.273048] Stack : 804e765a 00000042 00000000 00000001 8658d724 8046b327 8041e800 000009cf
[542459.281842]         804e37a0 00000460 87658fcc 00000001 87658fcc 800a9240 80424030 80470000
[542459.290631]         00000003 00000460 804221e8 86671aac 87658fcc 800d6f6c 804e765a 00000076
[542459.299421]         8047d000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.308211]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.317000]         ...
[542459.319626] Call Trace:
[542459.322240] [<8006b0f0>] show_stack+0x70/0x8c
[542459.326853] [<80080064>] __warn+0x110/0x118
[542459.331266] [<80080100>] warn_slowpath_null+0x1c/0x2c
[542459.336688] [<87787270>] __sta_info_flush+0x158/0x198 [mac80211]
[542459.343063] [<8779c4b4>] ieee80211_nan_func_match+0x1964/0x27d0 [mac80211]
[542459.350326] ---[ end trace d2e6a234c6756786 ]---
[542459.468168] device wlan1-1 left promiscuous mode
[542459.473387] br-wan: port 2(wlan1-1) entered disabled state
[542459.489359] ------------[ cut here ]------------
[542459.494539] WARNING: CPU: 0 PID: 2511 at backports-2017-11-01/net/mac80211/sta_info.c:940 ieee80211_sta_eosp+0x65c/0xa34 [mac80211]
[542459.506900] Modules linked in: ath9k nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute ath9k_common ath10k_pci ath10k_core xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mac80211 iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 br_netfilter ath9k_hw ath em_cmp em_nbyte sch_dsmark sch_pie sch_gred em_meta sch_teql
[542459.580542]  act_ipt sch_multiq sch_prio em_text sch_codel sch_red sch_sfq sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_htb sch_hfsc ledtrig_usbport batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables dummy ip_tunnel veth tun vxlan udp_tunnel ip6_udp_tunnel ehci_platform ehci_hcd act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug usbcore nls_base usb_common crc16 crc32c_generic crypto_hash
[542459.628011] CPU: 0 PID: 2511 Comm: hostapd Tainted: G        W       4.9.87 #0
[542459.635557] Stack : 804e765a 00000042 00000000 00000001 8658d724 8046b327 8041e800 000009cf
[542459.644345]         804e37a0 000003ac 87658fcc 00000000 87658fcc 800a9240 80424030 80470000
[542459.653134]         00000003 000003ac 804221e8 86671bbc 87658fcc 800d6f6c 804e765a 00000077
[542459.661925]         8047d000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.670714]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.679503]         ...
[542459.682131] Call Trace:
[542459.684746] [<8006b0f0>] show_stack+0x70/0x8c
[542459.689360] [<80080064>] __warn+0x110/0x118
[542459.693769] [<80080100>] warn_slowpath_null+0x1c/0x2c
[542459.699198] [<87783ed4>] ieee80211_sta_eosp+0x65c/0xa34 [mac80211]
[542459.705735] ---[ end trace d2e6a234c6756787 ]---
[542459.710606] ------------[ cut here ]------------
[542459.715527] WARNING: CPU: 0 PID: 2511 at backports-2017-11-01/net/mac80211/sta_info.c:1120 __sta_info_flush+0x158/0x198 [mac80211]
[542459.727744] Modules linked in: ath9k nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute ath9k_common ath10k_pci ath10k_core xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mac80211 iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 br_netfilter ath9k_hw ath em_cmp em_nbyte sch_dsmark sch_pie sch_gred em_meta sch_teql
[542459.801379]  act_ipt sch_multiq sch_prio em_text sch_codel sch_red sch_sfq sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_htb sch_hfsc ledtrig_usbport batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables dummy ip_tunnel veth tun vxlan udp_tunnel ip6_udp_tunnel ehci_platform ehci_hcd act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug usbcore nls_base usb_common crc16 crc32c_generic crypto_hash
[542459.848838] CPU: 0 PID: 2511 Comm: hostapd Tainted: G        W       4.9.87 #0
[542459.856383] Stack : 804e765a 00000042 00000000 00000001 8658d724 8046b327 8041e800 000009cf
[542459.865163]         804e37a0 00000460 87658fcc 00000000 87658fcc 800a9240 80424030 80470000
[542459.873954]         00000003 00000460 804221e8 86671bec 87658fcc 800d6f6c 804e765a 00000076
[542459.882743]         8047d000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.891533]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542459.900323]         ...
[542459.902950] Call Trace:
[542459.905572] [<8006b0f0>] show_stack+0x70/0x8c
[542459.910185] [<80080064>] __warn+0x110/0x118
[542459.914597] [<80080100>] warn_slowpath_null+0x1c/0x2c
[542459.920018] [<87787270>] __sta_info_flush+0x158/0x198 [mac80211]
[542459.926428] [<87795208>] ieee80211_del_virtual_monitor+0x198/0x8d8 [mac80211]
[542459.933927] ---[ end trace d2e6a234c6756788 ]---
[542459.938799] ------------[ cut here ]------------
[542459.943727] WARNING: CPU: 0 PID: 2511 at backports-2017-11-01/net/mac80211/iface.c:857 ieee80211_del_virtual_monitor+0x2a0/0x8d8 [mac80211]
[542459.956752] Modules linked in: ath9k nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute ath9k_common ath10k_pci ath10k_core xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mac80211 iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 br_netfilter ath9k_hw ath em_cmp em_nbyte sch_dsmark sch_pie sch_gred em_meta sch_teql
[542460.030378]  act_ipt sch_multiq sch_prio em_text sch_codel sch_red sch_sfq sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_htb sch_hfsc ledtrig_usbport batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables dummy ip_tunnel veth tun vxlan udp_tunnel ip6_udp_tunnel ehci_platform ehci_hcd act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug usbcore nls_base usb_common crc16 crc32c_generic crypto_hash
[542460.077828] CPU: 0 PID: 2511 Comm: hostapd Tainted: G        W       4.9.87 #0
[542460.085365] Stack : 804e765a 00000042 00000000 00000001 8658d724 8046b327 8041e800 000009cf
[542460.094155]         804e37a0 00000359 00000001 7fe3ed3c 00000000 800a9240 80424030 80470000
[542460.102944]         00000003 00000359 804221e8 86671c2c 00000000 800d6f6c 804e765a 0000007f
[542460.111734]         8047d000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542460.120533]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[542460.129323]         ...
[542460.131949] Call Trace:
[542460.134563] [<8006b0f0>] show_stack+0x70/0x8c
[542460.139174] [<80080064>] __warn+0x110/0x118
[542460.143587] [<80080100>] warn_slowpath_null+0x1c/0x2c
[542460.149014] [<87795310>] ieee80211_del_virtual_monitor+0x2a0/0x8d8 [mac80211]
[542460.156547] ---[ end trace d2e6a234c6756789 ]---
[542460.195746] ath10k_pci 0000:00:00.0: peer-unmap-event: unknown peer id 1
[542460.202818] ath10k_pci 0000:00:00.0: peer-unmap-event: unknown peer id 1
[542460.217579] ath10k_pci 0000:00:00.0: peer-unmap-event: unknown peer id 1
[542460.224607] ath10k_pci 0000:00:00.0: received addba event for invalid peer_id: 77
[542460.232463] ath10k_pci 0000:00:00.0: peer-unmap-event: unknown peer id 77
[542460.379642] batman_adv: bat0: Interface deactivated: mesh1
[542460.526110] batman_adv: bat0: Removing interface: mesh1
[542466.812951] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[542466.840152] IPv6: ADDRCONF(NETDEV_UP): wlan1-1: link is not ready
[542466.857494] br-wan: port 2(wlan0) entered blocking state
[542466.863084] br-wan: port 2(wlan0) entered disabled state
[542466.869091] device wlan0 entered promiscuous mode
[542466.881733] br-wan: port 3(wlan1-1) entered blocking state
[542466.887550] br-wan: port 3(wlan1-1) entered disabled state
[542466.893672] device wlan1-1 entered promiscuous mode
[542467.824155] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[542467.831047] br-wan: port 2(wlan0) entered blocking state
[542467.836667] br-wan: port 2(wlan0) entered forwarding state
[542467.842590] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1-1: link becomes ready
[542467.849606] br-wan: port 3(wlan1-1) entered blocking state
[542467.855366] br-wan: port 3(wlan1-1) entered forwarding state
[542467.865351] br-client: port 4(client0) entered blocking state
[542467.871455] br-client: port 4(client0) entered disabled state
[542467.877859] device client0 entered promiscuous mode
[542467.901081] br-client: port 5(client1) entered blocking state
[542467.907171] br-client: port 5(client1) entered disabled state
[542467.913587] device client1 entered promiscuous mode
[542467.930054] IPv6: ADDRCONF(NETDEV_UP): client0: link is not ready
[542467.936520] br-client: port 4(client0) entered blocking state
[542467.942547] br-client: port 4(client0) entered forwarding state
[542467.976790] IPv6: ADDRCONF(NETDEV_UP): client1: link is not ready
[542467.983371] br-client: port 5(client1) entered blocking state
[542467.989444] br-client: port 5(client1) entered forwarding state
[542468.014623] br-client: port 4(client0) entered disabled state
[542468.044176] br-client: port 5(client1) entered disabled state
[542468.063771] IPv6: ADDRCONF(NETDEV_CHANGE): client0: link becomes ready
[542468.070862] br-client: port 4(client0) entered blocking state
[542468.076925] br-client: port 4(client0) entered forwarding state
[542468.113392] IPv6: ADDRCONF(NETDEV_CHANGE): client1: link becomes ready
[542468.120447] br-client: port 5(client1) entered blocking state
[542468.126533] br-client: port 5(client1) entered forwarding state
[542468.437877] IPv6: ADDRCONF(NETDEV_UP): mesh1: link is not ready
[542468.775171] IPv6: ADDRCONF(NETDEV_CHANGE): mesh1: link becomes ready
[542469.942797] batman_adv: bat0: Adding interface: mesh1
[542469.948190] batman_adv: bat0: Interface activated: mesh1
root@E09-HH-2OG-1:~# wifi
root@E09-HH-2OG-1:~# wifi
root@E09-HH-2OG-1:~# 
root@E09-HH-2OG-1:~# 
root@E09-HH-2OG-1:~# 
root@E09-HH-2OG-1:~# 
root@E09-HH-2OG-1:~# packet_write_wait: Connection to 192.168.1.xxx port 22: Broken pipe
user@pc:~$ ssh root@192.168.1.xxx


BusyBox v1.27.2 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r6567+7-db893ec
 -----------------------------------------------------
root@E09-HH-2OG-1:~# 
```

**Comment by rotanid** [comment] 2018-05-03 23:07
"based on OpenWrt trunk" - so you're running a firmware based on the "next" branch of Gluon?
if yes, could you please report if the issue also affects you if you user Gluons "master" branch?
so far, the master branch is our main focus

**Comment by mokkin** [comment] 2018-05-04 06:33
As far as I know, the master branch is based on LEDE 17.01 release. In this release the device (Archer c59) wasn't included, so I decided to compile gluon-next with OpenWRT to receive an image for the device and having the latest bugfixes.
Should I try it again with master?

**Comment by rotanid** [comment] 2018-05-04 08:30
we have support in the master branch:
https://github.com/freifunk-gluon/gluon/blob/master/targets/ar71xx-generic#L197
it was integrated with this PR in January:
https://github.com/freifunk-gluon/gluon/pull/1281

**Comment by rotanid** [comment] 2018-05-25 02:04
as at least three devices of the model Archer C59 are running here with master branch without problems, the problem might be in the "next" branch only or related to the specific site.conf/site.mk of @mokkin

**Comment by mokkin** [comment] 2018-06-12 19:21
I have built a new gluon based on master as requested. I'll let you know about the results.

**Comment by rotanid** [comment] 2018-07-12 02:38
@mokkin any update on this? can we close the issue?

**Comment by mokkin** [comment] 2018-07-12 10:17
Actually not. We are still observing the issue.

**Comment by blocktrron** [comment] 2018-07-12 11:09
@mokkin can you observe this issue on multiple devices? I've tried an C58 and a C59 and was not able to reproduce this issue. Is it working without Private WiFi enabled?

**Closed** 2018-08-22 23:26 UTC
Labels: awaiting answer, bug, hardware
