### ISSUE TITLE
respondd does not listen on br-client

### ISSUE THREAD

**Issue by jplitza** [freifunk-gluon/gluon#1142] opened 2017-06-17 13:04 UTC
After the update to 2016.2.6 (but probably not really related to that), the respondd on one of my nodes was started with these arguments:
```
 1825 root      2260 S    /usr/bin/respondd -g ff02::2:1001 -p 1001 -d /lib/gluon/respondd -i ibss0 -i br-wan
```
While by itself this is okay, it should have been restarted when the client interface came up. But it wasn't. Executing `/etc/init.d/gluon-respondd reload` correctly included the interface `-i br-client` in the argument list, meaning that the argument building in the init script seems to work.

I suspect a race condition on startup: The init script fetches the list of interfaces while the client interface is still down, but before it finishes, the interface comes up and procd doesn't execute the reload because the first run of the init script hasn't exited yet.

*Update*: I'm a bit puzzled, because apparently the node answered for quite a while after upgrade (the increase in RAM usage), but the respondd process was never restartet according to the timestamps in `/proc/$(pidof respondd)`
![grafik](https://user-images.githubusercontent.com/3628012/27253134-10188bdc-536f-11e7-8e3f-3a4d31ae3265.png)

**Comment by mweinelt** [comment] 2018-11-26 01:12
Is this issue reproducible and still relevant?

**Comment by NeoRaider** [comment] 2018-11-30 20:08
The code has changed significantly since 2016.2.x. Closing until further notice.

**Closed by NeoRaider** 2018-11-30 20:08 UTC
Labels: bug
