### ISSUE TITLE
batman-adv crash when removing interface

### ISSUE THREAD

**Issue by plumpudding** [freifunk-gluon/gluon#910] opened 2016-10-20 12:02 UTC
logread:
```
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.210000] IPv6: ADDRCONF(NETDEV_UP): mesh0: link is not ready
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.280000] IPv6: ADDRCONF(NETDEV_CHANGE): mesh0: link becomes ready
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Network device 'mesh0' link is up
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_radio0' is enabled
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_radio0' has link connectivity 
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_radio0' is setting up now
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.450000] eth0: link up (1000Mbps/Full duplex)
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.450000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Network device 'eth0' link is up
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.470000] br-wan: port 1(eth0.1) entered forwarding state
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.470000] br-wan: port 1(eth0.1) entered forwarding state
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.480000] br-mesh_lan: port 1(eth0.2) entered forwarding state
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.480000] br-mesh_lan: port 1(eth0.2) entered forwarding state
Mon Oct 10 22:44:37 2016 daemon.notice netifd: VLAN 'eth0.1' link is up
Mon Oct 10 22:44:37 2016 daemon.notice netifd: VLAN 'eth0.2' link is up
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'client_lan' has link connectivity 
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'client_lan' is setting up now
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.490000] IPv6: ADDRCONF(NETDEV_CHANGE): br-wan: link becomes ready
Mon Oct 10 22:44:37 2016 kern.info kernel: [   29.500000] IPv6: ADDRCONF(NETDEV_CHANGE): br-mesh_lan: link becomes ready
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'client_lan' is now up
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Bridge 'br-wan' link is up
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'wan6' has link connectivity 
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'wan6' is setting up now
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'wan' has link connectivity 
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'wan' is setting up now
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_wan' has link connectivity 
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_wan' is setting up now
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Bridge 'br-mesh_lan' link is up
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_lan' has link connectivity 
Mon Oct 10 22:44:37 2016 daemon.notice netifd: Interface 'mesh_lan' is setting up now
Mon Oct 10 22:44:38 2016 daemon.notice netifd: wan (1735): udhcpc (v1.23.2) started
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.790000] batman_adv: bat0: Adding interface: primary0
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.800000] batman_adv: bat0: Interface activated: primary0
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.850000] batman_adv: bat0: Adding interface: br-wan
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.860000] batman_adv: bat0: The MTU of interface br-wan is too small (1500) to handle the transport of batman-adv packets. Packets going over this interface will be fragmented on layer2 which could impact the performance. Setting the MTU to 1532 would solve the problem.
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.880000] batman_adv: bat0: Interface activated: br-wan
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.920000] batman_adv: bat0: Adding interface: mesh0
Mon Oct 10 22:44:38 2016 kern.info kernel: [   30.930000] batman_adv: bat0: Interface activated: mesh0
Mon Oct 10 22:44:38 2016 daemon.notice netifd: Interface 'bat0' is enabled
Mon Oct 10 22:44:38 2016 kern.info kernel: [   31.020000] 8021q: adding VLAN 0 to HW filter on device bat0
Mon Oct 10 22:44:38 2016 kern.info kernel: [   31.030000] device bat0 entered promiscuous mode
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.070000] batman_adv: bat0: Adding interface: br-mesh_lan
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.070000] batman_adv: bat0: The MTU of interface br-mesh_lan is too small (1500) to handle the transport of batman-adv packets. Packets going over this interface will be fragmented on layer2 which could impact the performance. Setting the MTU to 1532 would solve the problem.
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.100000] batman_adv: bat0: Interface activated: br-mesh_lan
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.140000] br-client: port 1(bat0) entered forwarding state
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.150000] br-client: port 1(bat0) entered forwarding state
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'client' is enabled
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.210000] device br-client entered promiscuous mode
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'local_node' is enabled
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'local_node' is setting up now
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'local_node' is now up
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'mesh_radio0' is now up
Mon Oct 10 22:44:39 2016 daemon.notice netifd: mesh_lan (1714): ip: RTNETLINK answers: File exists
Mon Oct 10 22:44:39 2016 daemon.notice netifd: wan (1735): Sending discover...
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Network device 'bat0' link is up
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'bat0' has link connectivity 
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'bat0' is setting up now
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'bat0' is now up
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.300000] batman_adv: bat0: no_rebroadcast: Changing from: disabled to: enabled
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Bridge 'br-client' link is up
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'client' has link connectivity 
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'client' is setting up now
Mon Oct 10 22:44:39 2016 daemon.notice netifd: MAC VLAN 'local-node' link is up
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'local_node' has link connectivity 
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'mesh_wan' is now up
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.470000] br-wan: port 1(eth0.1) entered forwarding state
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.480000] br-mesh_lan: port 1(eth0.2) entered forwarding state
Mon Oct 10 22:44:39 2016 daemon.notice netifd: Interface 'mesh_lan' is now up
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.810000] batman_adv: bat0: Changing gw mode from: off to: client
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.850000] batman_adv: bat0: hop_penalty: Changing from: 30 to: 15
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.850000] batman_adv: bat0: multicast_mode: Changing from: enabled to: disabled
Mon Oct 10 22:44:39 2016 kern.info kernel: [   31.880000] batman_adv: bat0: orig_interval: Changing from: 1000 to: 5000
Mon Oct 10 22:44:39 2016 user.notice sysctl: net.ipv6.conf.br-client.forwarding = 0
Mon Oct 10 22:44:40 2016 user.notice firewall: Reloading firewall due to ifup of local_node (local-node)
Mon Oct 10 22:44:41 2016 kern.info kernel: [   33.150000] br-client: port 1(bat0) entered forwarding state
Mon Oct 10 22:44:42 2016 kern.info kernel: [   34.190000] eth0: link down
Mon Oct 10 22:44:42 2016 kern.info kernel: [   34.190000] br-wan: port 1(eth0.1) entered disabled state
Mon Oct 10 22:44:42 2016 kern.info kernel: [   34.190000] br-mesh_lan: port 1(eth0.2) entered disabled state
Mon Oct 10 22:44:42 2016 daemon.notice netifd: Network device 'eth0' link is down
Mon Oct 10 22:44:42 2016 daemon.notice netifd: VLAN 'eth0.1' link is down
Mon Oct 10 22:44:42 2016 daemon.notice netifd: VLAN 'eth0.2' link is down
Mon Oct 10 22:44:42 2016 daemon.notice netifd: Interface 'client_lan' has link connectivity loss
Mon Oct 10 22:44:42 2016 daemon.notice netifd: Interface 'client_lan' is now down
Mon Oct 10 22:44:42 2016 daemon.notice netifd: wan (1735): Sending discover...
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Bridge 'br-wan' link is down
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'wan6' has link connectivity loss
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'wan' has link connectivity loss
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'mesh_wan' has link connectivity loss
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Bridge 'br-mesh_lan' link is down
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'mesh_lan' has link connectivity loss
Mon Oct 10 22:44:43 2016 daemon.notice netifd: wan (1735): Received SIGTERM
Mon Oct 10 22:44:43 2016 kern.info kernel: [   35.690000] eth0: link up (1000Mbps/Full duplex)
Mon Oct 10 22:44:43 2016 kern.info kernel: [   35.690000] br-wan: port 1(eth0.1) entered forwarding state
Mon Oct 10 22:44:43 2016 kern.info kernel: [   35.700000] br-wan: port 1(eth0.1) entered forwarding state
Mon Oct 10 22:44:43 2016 kern.info kernel: [   35.700000] br-mesh_lan: port 1(eth0.2) entered forwarding state
Mon Oct 10 22:44:43 2016 kern.info kernel: [   35.710000] br-mesh_lan: port 1(eth0.2) entered forwarding state
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Network device 'eth0' link is up
Mon Oct 10 22:44:43 2016 daemon.notice netifd: VLAN 'eth0.1' link is up
Mon Oct 10 22:44:43 2016 daemon.notice netifd: VLAN 'eth0.2' link is up
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'client_lan' has link connectivity 
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'client_lan' is setting up now
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'client_lan' is now up
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Bridge 'br-wan' link is up
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'wan6' has link connectivity 
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'wan6' is setting up now
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'wan' has link connectivity 
Mon Oct 10 22:44:43 2016 daemon.notice netifd: Interface 'wan' is setting up now
Mon Oct 10 22:44:43 2016 kern.info kernel: [   36.040000] batman_adv: bat0: Interface deactivated: br-wan
Mon Oct 10 22:44:43 2016 kern.info kernel: [   36.050000] batman_adv: bat0: Removing interface: br-wan
Mon Oct 10 22:44:44 2016 daemon.notice netifd: Interface 'mesh_wan' is now down
Mon Oct 10 22:44:44 2016 daemon.notice netifd: Interface 'mesh_wan' is setting up now
Mon Oct 10 22:44:44 2016 kern.info kernel: [   36.140000] batman_adv: bat0: Interface deactivated: br-mesh_lan
Mon Oct 10 22:44:44 2016 kern.info kernel: [   36.150000] batman_adv: bat0: Removing interface: br-mesh_lan
Mon Oct 10 22:44:44 2016 kern.err kernel: [   36.180000] tried to remove device eth0 from local-node
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Kernel bug detected[#1]:
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] CPU: 0 PID: 2104 Comm: config_mesh_int Not tainted 3.18.29 #3
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] task: 8394d838 ti: 82dbc000 task.ti: 82dbc000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $ 0   : 00000000 00000001 0000002b 00000000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $ 4   : 803b6254 803b6254 803b6510 801d99e4
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $ 8   : 00000065 65206574 68302066 726f6d20
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $12   : 00000000 00000001 00000000 6e9f195d
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $16   : 00000000 83827800 83355800 83827860
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $20   : 82c42068 82d19060 82d19440 00000000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $24   : 00000002 801d8eb8                  
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] $28   : 82dbc000 82dbddb8 7fd364e0 802389b8
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Hi    : 00000000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Lo    : 7848e000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] epc   : 802389b8 __netdev_adjacent_dev_remove+0x4c/0x138
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000]     Not tainted
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] ra    : 802389b8 __netdev_adjacent_dev_remove+0x4c/0x138
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Status: 1100e403	KERNEL EXL IE 
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Cause : 00800024
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] PrId  : 0001974c (MIPS 74Kc)
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Modules linked in: iptable_nat ath9k nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute ath9k_common xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrackMon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Process config_mesh_int (pid: 2104, threadinfo=82dbc000, task=8394d838, tls=776b5440)
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Stack : 6c6f7765 83827800 83355800 00000000 6e000000 83827800 83355800 82ccec80
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 	  83263a00 8023aa34 832fb280 830918d0 838c8980 82c42000 82d19000 82c42000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 	  82d19000 8023ab3c 00000000 00000000 838c8980 838c8980 838c8980 838c8980
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 	  838c8980 838c8998 83174780 82d19000 00000001 8308a030 7fd36578 82d19000
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 	  82c42000 00000000 7fd364e0 8010a51c 838c8998 838c8980 83252200 00000004
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 	  ...
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Call Trace:
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] [<802389b8>] __netdev_adjacent_dev_remove+0x4c/0x138
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] [<8023aa34>] __netdev_adjacent_dev_unlink+0x20/0x40
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] [<8023ab3c>] netdev_upper_dev_unlink+0x9c/0x13c
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] [<8308a030>] batadv_hardif_disable_interface+0x25c/0x87c [batman_adv]
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] [<83094acc>] batadv_softif_is_valid+0xf9c/0x1270 [batman_adv]
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] 
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.180000] Code: 02202821  0c028f52  02403021 <000c000d> 94420006  2c430002  14600009  2442ffff  a6020006 
Mon Oct 10 22:44:44 2016 kern.warn kernel: [   36.470000] ---[ end trace eb65eba8391fc44e ]---
Mon Oct 10 22:44:44 2016 daemon.notice netifd: wan (2130): udhcpc (v1.23.2) started
Mon Oct 10 22:44:44 2016 daemon.notice netifd: wan (2130): Sending discover...
Mon Oct 10 22:44:44 2016 daemon.notice netifd: mesh_lan (2094): Segmentation fault
Mon Oct 10 22:44:44 2016 daemon.notice netifd: Interface 'mesh_lan' is now down
Mon Oct 10 22:44:45 2016 kern.info kernel: [   37.700000] br-wan: port 1(eth0.1) entered forwarding state
Mon Oct 10 22:44:45 2016 kern.info kernel: [   37.710000] br-mesh_lan: port 1(eth0.2) entered forwarding state
Mon Oct 10 22:44:52 2016 kern.notice kernel: [   44.650000] random: nonblocking pool is initialized
Mon Oct 10 22:51:41 2016 kern.info kernel: [  453.480000] eth0: link down
Mon Oct 10 22:54:02 2016 kern.warn kernel: [  594.810000] br-client: Multicast hash table maximum of 512 reached, disabling snooping: bat0
Mon Oct 10 23:23:27 2016 kern.info kernel: [ 2359.980000] eth0: link up (1000Mbps/Full duplex)
Mon Oct 10 23:23:29 2016 kern.info kernel: [ 2361.480000] eth0: link down
Mon Oct 10 23:23:32 2016 kern.info kernel: [ 2364.480000] eth0: link up (1000Mbps/Full duplex)
Mon Oct 10 23:23:35 2016 kern.info kernel: [ 2367.480000] eth0: link down
Mon Oct 10 23:23:36 2016 kern.info kernel: [ 2368.980000] eth0: link up (1000Mbps/Full duplex)
Mon Oct 10 23:23:49 2016 kern.info kernel: [ 2381.980000] eth0: link down
Mon Oct 10 23:23:51 2016 kern.info kernel: [ 2383.480000] eth0: link up (1000Mbps/Full duplex)
Mon Oct 10 23:23:56 2016 kern.info kernel: [ 2388.980000] eth0: link down
```

The node didn't reboot, so it became a zombie node. 

Commit: a54e7654cda80c8b9ea3fc991719c1e254c4f995
Node: https://bgl.map.ffgl.eu/#!v:g;n:c4e984b0d632
This has happened multiple times. 
The shell gets stuck when typing "ip a"

**Comment by NeoRaider** [comment] 2016-10-20 12:05
Duplicate of #680

**Closed by NeoRaider** 2016-10-20 12:05 UTC
