### ISSUE TITLE
building ar71xx-tiny fails due to d-link-dir-615

### ISSUE THREAD

**Issue by gherber** [freifunk-gluon/gluon#1019] opened 2017-01-30 20:10 UTC
building the current master (1222c38) fails with the following error:
make[1]: Leaving directory '/home/georges/repo/fflux/gluon/lede'
cp: cannot stat 'lede/bin/targets/ar71xx/generic/lede-ar71xx-generic-dir-615-c1-squashfs-factory.bin': No such file or directory
Makefile:120: recipe for target 'all' failed
make: *** [all] Error 1

complete build log: https://gist.githubusercontent.com/gherber/917d308aac66da25ab2d67f6fe576894/raw/f25f7e0ed5d44276aa07207652ed993fd3a623c3/build.log
when commenting out the d-link-dir-615-rev-c1 device in targets/ar71xx-tiny, building the target is successful

**Comment by NeoRaider** [comment] 2017-01-30 20:20
Duplicate of #1009, it fails because the image is too big. I'm currently working on reducing the size of the LuCI libraries used by the config mode; until that's done I can only recommend to remove additional languages and packages from your *site.mk*.

**Closed by NeoRaider** 2017-01-30 20:20 UTC
