### ISSUE TITLE
hiveaps don't survive autoupdate to new releases (from v2019/v2021)

### ISSUE THREAD

**Issue by Djfe** [freifunk-gluon/gluon#3181] opened 2024-02-04 10:09 UTC
In Aachen we lost 100% of our Hive APs during migration to newer releases.
5x HiveAP 121
2x HiveAP 330

the 330s were lost on update from v2019 to v2021.
They are both installed at the same spot but we only managed to find one so far.
A powercycle was enough to bring it back to live.
We lost it again a couple days later on the update from v2021 to v2023.1.

The 121s updated just fine from v2019 to v2021 but were lost a couple days later, when we rolled out v2023.1 for them.

We haven't really gotten hands on the devices, yet.
But we wanted to let people know about this issue :)
If we get hands on, then we'll retest our migration and watch logs and we will also test v2023.2

**Comment by Djfe** [comment] 2024-02-04 10:22
Update:
330 got a major raise in compat version on OpenWrt release 22
https://github.com/openwrt/openwrt/commit/cfe79f2eb8b3c874f3d1a4441b8a60af32169974

I have no clue why they went offline then unless they weren't able to reactivate wifi (for meshing) after trying to install the sysupgrade. (which probably gets tried every hour)

**Comment by kpanic23** [comment] 2024-02-04 12:15
Apparently it's a bug in the autoupdater: The Image check fails after all network has stopped, but network isn't started again after the failure, so the device is left without any network connectivity.
https://github.com/freifunk-gluon/gluon/issues/2742#issuecomment-1780898705

**Comment by rotanid** [comment] 2024-02-04 14:54
the actual issue is described in #2742 as @kpanic23 already wrote. you have to act manually on site.
@neocturne do you think the autoupdate might really be an issue here like @kpanic23 says? at the least the devices should continue to run with the old firmware...

**Comment by rotanid** [comment] 2024-02-04 17:05
hm, this issue is simply not true as they "survive" it other than stated.
and if the issue with the 121 is the same, we don't need two issues for the same thing.
rather a new one about the autoupdater - if it actually is a bug there.

regarding known issues: you can answer it yourself by looking at the past release notes ;-)
at least the issue is marked as a known issue on github since 2023-10-27

**Comment by kpanic23** [comment] 2024-02-05 03:13
> ... at the least the devices should continue to run with the old firmware...
Technically they do. The problem is that the autoupdater stops networking before the update, aborts because of image version mismatch and just exits without re-enabling networking. This results in the node fully running but without any network connectivity. I've removed the image from our update server, so the nodes don't get stuck every hour again trying to upgrade.
If this gets fixed in autoupdater, the fix should probably get backported to 2021.1.x as well, just for safekeeping.

**Comment by blocktrron** [comment] 2024-02-05 14:23
@kpanic23 This was fixed with https://github.com/freifunk-gluon/packages/commit/0648b2dbf71c16127ae498cc14f1d33c3f95c741

**Comment by rotanid** [comment] 2024-02-05 19:32
> @kpanic23 This was fixed with [freifunk-gluon/packages@0648b2d](https://github.com/freifunk-gluon/packages/commit/0648b2dbf71c16127ae498cc14f1d33c3f95c741)

oh wow, and reported by myself over 5 years ago...
somehow we missed to backport it, d'oh!

**Comment by rotanid** [comment] 2024-05-11 22:15
@Djfe can we close this issue?

**Comment by blocktrron** [comment] 2024-07-06 12:22
Closed as not a bug.

**Closed by blocktrron** 2024-07-06 12:22 UTC

**Comment by kpanic23** [comment] 2024-07-06 13:55
> the openwrt name changed slightly in ath79 The manifest is correct but the sysupgrade doesn't have the metadata for the old ar71xx name

I just had a look at our firmware archive. It's been "aerohive-hiveap-121" since v2018.2.3, no change at all.
