### ISSUE TITLE
sign.sh not working with new ecdsautil version

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#633] opened 2016-01-28 23:17 UTC
https://github.com/freifunk-gluon/gluon/blob/e5d6ec73f5ebfb012912a545daf0cbd0205c4638/contrib/sign.sh

If you checkout master of `ecdsautil` the syntax has changed, so there should be either a hint to checkout Release v0.3.2 or the new syntaxshould be added in the contrib file.

an alround solution would be if the shell script checks the version of `ecdsautil` before the sign command

**Comment by jplitza** [comment] 2016-01-29 09:15
Duplicate of #571, #572 and #630. Please read the comments of especially the last one.

**Closed by jplitza** 2016-01-29 09:15 UTC
