### ISSUE TITLE
Ubiquiti ER-X SFP shows (private) WLAN settings and VPN key N/A

### ISSUE THREAD

**Issue by 2tata** [freifunk-gluon/gluon#2176] opened 2021-01-23 22:20 UTC
The ER-x SFP shows wifi settings. Which should not shown as the device does not have any Wifi chip.

Another minor issue the VPN key on the information screen and on the reboot page is always shown as N/A (tunneldigger). 

![image](https://user-images.githubusercontent.com/3101274/105615462-2c6fbb00-5dd1-11eb-8f3c-369eaa9a8d3d.png)

![image](https://user-images.githubusercontent.com/3101274/105615468-37c2e680-5dd1-11eb-98bc-30a31c926cc8.png)

![image](https://user-images.githubusercontent.com/3101274/105615470-40b3b800-5dd1-11eb-8072-600567185c41.png)

**Comment by blocktrron** [comment] 2021-01-23 22:50
@2tata regarding the VPN key: Which VPN provider (tunneldigger / fastd) are you using?

**Comment by 2tata** [comment] 2021-01-23 22:52
@blocktrron I have updated the above discription

**Comment by AiyionPrime** [comment] 2022-01-25 17:33
The vpn key does not lead to problems with wireguard;
but I can confirm the wifi-related-issue on an erx (no sfp)

gluon-v2021.1-148-gb7c343ac
gluon: 3f7c0b3ae8297541389a2512ac92ad5c1a02bbeb
site: https://github.com/freifunkh/site/commit/cb027748417b4e88fdbe96919feb213e31e4242c

**Comment by NeoRaider** [comment] 2022-01-25 17:41
The VPN key works as expected: Tunneldigger doesn't have a key, so "n/a" is displayed.

The WLAN part was fixed with #2312 (#2311 was actually a duplicate of this issue).

**Closed by NeoRaider** 2022-01-25 17:41 UTC
Labels: 0. type: bug, 3. topic: config-mode

**Comment by AiyionPrime** [comment] 2022-01-25 17:42
Was about to revoke this, thx. Saw #2312 just now. Sorry for the noise.
