### ISSUE TITLE
Ubiquiti Unifi AP Pro: WAN LAN swapped

### ISSUE THREAD

**Issue by Sunz3r** [freifunk-gluon/gluon#797] opened 2016-06-08 13:06 UTC
Hi :)

WAN-Port should be the PoE-In-Port and the secondary-Port should be the LAN-Port

In previously versions the two ports were in the same VLAN:
```
config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0 1 2'

```

Current Version:
```
config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0t 1'

config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '0t 2'
```

**Comment by NeoRaider** [comment] 2016-06-08 17:25
Duplicate of #764, fixed in cab23b18381b593a72a6f70b737f7c4f34b75ffa.

**Closed by NeoRaider** 2016-06-08 17:25 UTC
