### ISSUE TITLE
x86 upgrade scheitert wegen Platzmangel

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#1131] opened 2017-06-01 00:15 UTC
siehe: https://pastebin.com/JDeqcM2e

update x86-generic 2016.2.5 auf master.

**Comment by kpanic23** [comment] 2017-06-01 08:38
Duplicate of #1010?

**Comment by A-Kasper** [comment] 2017-06-01 08:42
Nein. #1010 ist gefixed. eigentlich.  Aber verm. Fehlerhaft
Ich weiss nicht wie das Upgrade gemacht wird, aber könnte es sein, dass 1 GB RAM und 1 GB CF sich schneiden?

**Comment by NeoRaider** [comment] 2017-06-01 12:02
The issue has nothing to do with RAM or flash size.

sysupgrade will tar up a small list of config files (see `sysupgrade -l`) and add store this tgz file in the kernel partition. It is possible that your unusual setup with additional packages greatly increased the number or size of configuration files. Check the size of the generated file using `sysupgrade -b /tmp/config.tgz`).

If your configuration is indeed too big, there is no way to fix this at the moment, as the old sysupgrade script of Gluon v2016.2.x can't deal with growing kernel partitions. The sysupgrade script has been improved in the Gluon master, so Gluon v2017.2 will be the first Gluon version with more space for configuration during sysupgrade...

**Comment by A-Kasper** [comment] 2017-06-01 13:13
12 -rw-r--r--    1 root     root       10.9K Jun  1 15:11 config.tgz


2017-06-01 14:02 GMT+02:00 Matthias Schiffer <notifications@github.com>:

**Comment by A-Kasper** [comment] 2017-06-01 13:14
I'll try the following:
1. check if factory image works
2. check upgrade on another maschine...

2017-06-01 15:13 GMT+02:00 Andre Kasper <ein.kasper@gmx.de>:

**Comment by NeoRaider** [comment] 2017-06-01 13:18
Please also check the size of the backup tgz *before* upgrading on the other machine.

**Comment by A-Kasper** [comment] 2017-06-01 13:57
other sizes from other futros: 
12,7k 
12,5k

**Comment by A-Kasper** [comment] 2017-06-01 18:51
we tried it with other machines.. always the same: 
https://pastebin.com/Cdhxjuj7

**Comment by NeoRaider** [comment] 2017-06-01 18:59
Please provide your upgrade image, so I can have a look at it.

**Comment by A-Kasper** [comment] 2017-06-01 19:06
you can find it here:
http://build.freifunk-bochum.de/ffbobeta/sysupgrade/broken

**Comment by NeoRaider** [comment] 2017-06-01 19:11
Reverted fcce9e529501e5952d8c62dae0fe009f36ad2878; closing, as we're now back at the original issue #1010.

**Closed by NeoRaider** 2017-06-01 19:11 UTC
