### ISSUE TITLE
builderror on fresh 2016.1.5 tagged on debian

### ISSUE THREAD

**Issue by viisauksena** [freifunk-gluon/gluon#793] opened 2016-05-31 06:26 UTC
...
```
make -C out BUILDTYPE=Release V=99                                                                                                [213/1817]
make[7]: Entering directory `/media/freifunk/firmware/gluon/openwrt/build_dir/host/node-v4.4.4/out'
  g++ '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DHAVE_OPENSSL=1' '-D__POSIX__'
 '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_POSIX_C_SOURCE=200112' -I../src -I../tools/msvs/genfiles -I../d
eps/uv/src/ares -I/media/freifunk/firmware/gluon/openwrt/build_dir/host/node-v4.4.4/out/Release/obj/gen -I../deps/v8 -I../deps/cares/include
 -I../deps/v8/include -I../deps/openssl/openssl/include -I../deps/zlib -I../deps/http_parser -I../deps/uv/include  -pthread -Wall -Wextra -W
no-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /me
dia/freifunk/firmware/gluon/openwrt/build_dir/host/node-v4.4.4/out/Release/.deps//media/freifunk/firmware/gluon/openwrt/build_dir/host/node-
v4.4.4/out/Release/obj.target/node/src/js_stream.o.d.raw   -c -o /media/freifunk/firmware/gluon/openwrt/build_dir/host/node-v4.4.4/out/Relea
se/obj.target/node/src/js_stream.o ../src/js_stream.cc
In file included from ../src/js_stream.h:6:0,
                 from ../src/js_stream.cc:1:
../src/stream_base.h:225:11: error: looser throw specifier for 'virtual node::StreamBase::~StreamBase()'
../src/stream_base.h:141:11: error:   overriding 'virtual node::StreamResource::~StreamResource() noexcept (true)'
In file included from ../src/js_stream.cc:1:0:
../src/js_stream.h:17:3: error: looser throw specifier for 'virtual node::JSStream::~JSStream()'
In file included from ../src/js_stream.h:6:0,
                 from ../src/js_stream.cc:1:
../src/stream_base.h:225:11: error:   overriding 'virtual node::StreamBase::~StreamBase() noexcept (true)'
make[7]: *** [/media/freifunk/firmware/gluon/openwrt/build_dir/host/node-v4.4.4/out/Release/obj.target/node/src/js_stream.o] Error 1
make[7]: Leaving directory `/media/freifunk/firmware/gluon/openwrt/build_dir/host/node-v4.4.4/out'
make[6]: *** [node] Error 2
```

**Comment by NeoRaider** [comment] 2016-05-31 06:52
Duplicate of #776.

**Closed by NeoRaider** 2016-05-31 06:52 UTC
